class Constants:
    JANUARY = "January"
    FEBRUARY = "February"
    MARCH = "March"
    APRIL = "April"
    MAY = "May"
    JUNE = "June"
    JULY = "July"
    AUGUST = "August"
    SEPTEMBER = "September"
    OCTOBER = "October"
    NOVEMBER = "November"
    DECEMBER = "December"

    STERIC = "*"
    RECEIPTS = "Receipts"
    RECEIPT = "Receipt"
    MARKET = "Market"
    GYM = "Gym"
    ACCOUNT = "Account"
    TRADING = "Trading"
    MONTH = "Month"
    FOLDER = "Folder"
    PATH = "Path"
    MOVE = "Move"
    IN = "In"
    OUT = "Out"
    CREATING = "Creating"
    NAME = "Name"


    # Bank & Wallet Names
    ALLIED_BANK = "Allied Bank"
    BANK_ALFALAH = "Bank Alfalah"
    EASY_PAISSA = "EasyPaissa"
    FASSET = "Fasset"
    FIRST_PAY = "First Pay"
    HBL_MICROFINANCE = "HBL Microfinance"
    JAZZ_CASH = "JazzCash"
    MASHREQ_BANK = "Mashreq Bank"
    MEEZAN_BANK = "Meezan Bank"
    NAYA_PAY = "NayaPay"
    PAYONEER = "Payoneer"
    PAK_QATAR_FINANCE = "Pak Qatar Finance"
    RAQAMI = "Raqami"
    SADA_PAY = "SadaPay"
    STANDARD_CHARTERED_BANK = "Standard Chartered Bank"
    U_PAISA = "UPaisa"
    ZINDIGI = "Zindigi"
